name: "Hosted: Network Filtering with Harden-Runner"
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            www.githubstatus.com:443

      - uses: crazy-max/ghaction-github-status@v4

      - uses: actions/checkout@v3

      - run: |
          curl https://exfiltrationdemo.blob.core.windows.net/
